### ISSUE TITLE
Problems with global install

### ISSUE THREAD

**Issue by jamesspittal** [jakefolio/csscodesniffer#2]
After installing `csscodesniffer` with:

```
# npm i -g csscodesniffer
```

I run:

```
# csscs ~/directory/assets/css/style.css
```

I get the following error:

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './standards/default.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.cli.getRuleset (/usr/local/lib/node_modules/csscodesniffer/src/cli.js:111:30)
    at Object.cli.getStandard (/usr/local/lib/node_modules/csscodesniffer/src/cli.js:102:21)
    at Object.cli.run (/usr/local/lib/node_modules/csscodesniffer/src/cli.js:59:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/csscodesniffer/src/cli.js:168:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

... which is odd because `default.json` is currently sitting in both locations below:

```
/root/.npm/csscodesniffer/0.1.1/package/src/standards/default.json
/usr/local/lib/node_modules/csscodesniffer/src/standards/default.json
```

Am I doing something silly wrong? (I'm relatively new to Node.js and `npm`, so it's entirely possible).

Thanks in advance.

**Comment by jakefolio** [comment]
It seems the way I'm loading in the standard and rules does not play well with global install. This was my first npm package, so learning experience. I can take a look at it, but it's going to take some refactoring to get it right.

**Comment by jamesspittal** [comment]
@jakefolio Thanks for your explanation - no need to re-factor, I'll see if I can reverse the global install and install it in the way suggested by the package.

To do so, I did:

```
# npm -g uninstall csscodesniffer
```

Then:

```
# npm install csscodesniffer
```

After doing so, I was able to get it working with:

```
# cd ~/node_modules/csscodesniffer/src
# ./cli.js ~/directory/assets/css/style.css
```

which produced the expected output like:

```
[L12:C17] One space after the colon is required
[L13:C21] One space after the colon is required
[L14:C1] Last property semicolon is required
[L15:C9] New line is required following declaration
[L16:C19] One space after the colon is required
[L18:C13] New line is required following declaration
[L19:C14] One space after the colon is required
[L20:C12] One space after the colon is required
[L22:C17] New line is required following declaration
[L23:C19] One space after the colon is required
[L24:C8] One space after the colon is required
[L25:C10] One space after the colon is required
[L26:C12] One space after the colon is required
[L28:C12] New line is required following declaration
```

Thanks @jakefolio - looks like it was just a problem with the global install as you suggested. Feel free to close this issue off if you like.
